server:
  port: 8090
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1
logging:
  level:
    root: info

spring:
  application:
    name: mall-gateway
  config:
    import:
      - nacos:mall-gateway?group=DEFAULT_GROUP
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        namespace: 5cfb9e33-bd54-4203-989b-a09c9e604a25
        access-key: VGhpc0lzTXlDdXN0b21TZWNyZXRLZXkwMTIzNDU2Nzg=
        refresh-enabled: true
        enabled: true
        file-extension: YAML
        enable-remote-sync-config: true
        group: DEFAULT_GROUP
      discovery:
        access-key: VGhpc0lzTXlDdXN0b21TZWNyZXRLZXkwMTIzNDU2Nzg=
        namespace: 5cfb9e33-bd54-4203-989b-a09c9e604a25
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: userRoute
              uri: lb://user-service
              predicates:
                - Path=/user/**,/passport/**,/admin/**
            - id: productRoute
              uri: lb://product-service
              predicates:
                - Path=/product/**
              filters:
                - StripPrefix=1
            - id: orderRoute
              uri: lb://order-service
              predicates:
                - Path=/order-service/**
            - id: payRoute
              uri: lb://pay-service
              predicates:
                - Path=/pay-service/**
            - id: cartRoute
              uri: lb://cart-service
              predicates:
                - Path=/cart-service/**
            - id: promotionRoute
              uri: lb://promotion-service
              predicates:
                - Path=/promotion-service/**
          globalcors:
            # 放行OPTIONS预检请求，核心配置
            add-to-simple-url-handler-mapping: true
            cors-configurations:
              '[/**]':
                # 替换为你的前端域名，多个逗号分隔，禁止*
                allowed-origin-patterns: "*"
                allowed-methods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowed-headers: "*"
                allow-credentials: true
                max-age: 3600